Support tab rotation for multiple sessions.
Remove secondsBetweenPages, rename isRaspberryPi check to isPiCheckReturnCode.

Add isPiCheckReturnCodeHardware for hardware checks to induce delays on
slower hardware.

Add endGraphicalSession in hopes that lightdm will relog immediately.
Otherwise will have to add logic for handling crashes or display layout
changes.

Rewrite cycleTabsIndefinitely to support the multiple Chromium windows
and rotating each of their tabs when applicable.

Modify all xdotool calls to include --clearmodifiers to avoid holding
keys down which could prevent Ctrl+Tabbing

Add DisplayLink USB detection and enumeration for activation.
Checks for driver presence but doesn't check for X11 configuration
support (Though config presence is implied from display presence when calling
randr --listproviders)

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,7 +1,6 @@
 #!/bin/bash
 _scriptRoot="$(dirname $(realpath $0))"
 _scriptName="$(basename ${_scriptRoot})"
-secondsBetweenPages=15
 x=1920
 y=1080
 
@@ -18,7 +17,7 @@ do
   case "$(tr '[:upper:]' '[:lower:]'<<<$1)" in
     -force) 
       echo "Forcing Pi-only commands to run."
-      isRaspberryPi=0 # returncode 0 = true
+      isPiCheckReturnCode=0
       ;;    
   esac
   shift
@@ -31,16 +30,28 @@ done
 # |_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 #
 
-function isRaspberryPi {
-  [ -n "$isRaspberryPi" ] && return $isRaspberryPi
+function isPiCheckReturnCode {
+  [ -n "$isPiCheckReturnCode" ] && return $isPiCheckReturnCode
 
   if grep -aiqs 'raspberry' /sys/firmware/devicetree/base/model
   then
-    isRaspberryPi=0 # true
+    isPiCheckReturnCode=0 # true
   else
-    isRaspberryPi=1 # false
+    isPiCheckReturnCode=1 # false
+    echo "Host does not appear to be a Raspberry Pi. Avoiding special commands intended for production use."
+    echo "Specify -force to bypass this check for use on non-pi systems."
   fi
+}
 
+function isPiCheckReturnCodeHardware {
+  [ -n "$isPiCheckReturnCodeHardware" ] && return $isPiCheckReturnCodeHardware
+
+  if grep -aiqs 'raspberry' /sys/firmware/devicetree/base/model
+  then
+    isPiCheckReturnCodeHardware=0 # true
+  else
+    isPiCheckReturnCodeHardware=1 # false
+  fi
 }
 
 function isTmpfs {
@@ -54,7 +65,7 @@ function closeTabNumber { # Could Alt+1 then Ctrl+Tab [x] times and Ctrl+W the r
   if [[ $1 =~ ^[0-9]$ ]]
   then
     echo "Closing tab: $1..."
-    xdotool search --onlyvisible --class Chromium key --delay 1000 --clearmodifiers Alt+${tabNumber} Ctrl+w
+    xdotool getactivewindow key --clearmodifiers --delay 1000 Alt+${tabNumber} Ctrl+w
     echo "Done."
   else
     echo "Tab number must be 0-9 for alt+# sequence."
@@ -63,15 +74,48 @@ function closeTabNumber { # Could Alt+1 then Ctrl+Tab [x] times and Ctrl+W the r
 
 function closeFirstTab { closeTabNumber 1 ;}
 
-function cycleTabsIndefinitely {
-  echo "Cycling tabs until chromium exits."
-  while [ -d /proc/${chromiumPid} ]
-  do
-    sleep ${tabbingInterval} # Sleeping first to stay on initial page for 15 as well.
-    xdotool search --onlyvisible --class Chromium key --clearmodifiers ctrl+Tab
-  done
+function endGraphicalSession {
+  case $XDG_SESSION_DESKTOP in
+    xfce)
+      xfce4-session-logout
+    ;;
+    gnome)
+      gnome-session-quit
+    ;;
+    *)
+      echo "Unsure how to exit $XDG_SESSION_DESKTOP"
+    ;;
+    esac
 
-  echo "Chromium has died [${chromiumPid}]. Exiting."
+}
+
+function cycleTabsIndefinitely {
+  echo "Cycling tabs until the chromium processes have exited..."
+
+  while pgrep chromium >/dev/null 2>&1
+  do
+    for configuredDisplayIndex in ${!configuredDisplays[@]}
+    do
+      targetPid=${connectedDisplaysChromiumPids[${configuredDisplayIndex}]}
+
+      if [ -d "/proc/" ]
+      then
+          # Ignore displays which don't have more than a single URL
+        if [ $(jq -r ".displays.\"${configuredDisplayIndex}\".urls | length" config.json) -gt 1 ] 
+        then
+	  windowId=$(xdotool search --pid ${targetPid} --onlyvisible | tail -n1)
+	  xdotool windowactivate ${windowId}
+	  xdotool key --clearmodifiers --window ${windowId} ctrl+Tab
+	fi
+      else
+        echo "Chromium for monitor ${configuredDisplayIndex} has died [${targetPid}]."
+	echo "Ending session to attempt recovery."
+	endGraphicalSession
+      fi
+    done
+
+    sleep ${tabbingInterval} # Sleeping first to stay on initial page for same delay too.
+  done
 }
 
 function siteHandler { # Knows how to log into different websites
@@ -79,22 +123,33 @@ function siteHandler { # Knows how to log into different websites
     *"logicmonitor.com"*)
       loginPageTitle="Logicmonitor Hosted Monitoring System - Chromium"
       echo "Waiting for page to finish loading..."
-      until [[ "$(xdotool getactivewindow getwindowname)" == "${loginPageTitle}" ]] ; do sleep 1 ; done
-      sleep 5 # Let the page finish drawing
+      until [[ "$(xdotool getactivewindow getwindowname)" == "${loginPageTitle}" ]] ; do sleep 0.5 ; done
+      isPiCheckReturnCodeHardware && sleep 5 || sleep 1 # If Pi let the page finish drawing.
       echo "Detected Logicmonitor login page. Logging in."
-      xdotool getactivewindow type "${username}"
-      xdotool getactivewindow key Tab
-      xdotool getactivewindow type "${password}"
-      xdotool getactivewindow key Return
+      xdotool getactivewindow type --clearmodifiers "${username}"
+      xdotool getactivewindow key  --clearmodifiers Tab
+      xdotool getactivewindow type --clearmodifiers "${password}"
+      xdotool getactivewindow key  --clearmodifiers Return
       echo "Waiting for next page to finish loading..."
-      until [[ "$(xdotool search --onlyvisible --class 'Chromium' getwindowname)" != "${loginPageTitle}" ]] ; do sleep 1 ; done
-      sleep 5 # Let the page finish drawing
+      until [[ "$(xdotool getactivewindow getwindowname)" != "${loginPageTitle}" ]] ; do sleep 1 ; done
+      isPiCheckReturnCodeHardware && sleep 5 || sleep 1 # If Pi let the page finish drawing.
       ;;
     *)
       echo "Unsure how to handle logins for page: \'${chromiumWindowTitle}\'. Ignoring."
       ;;
   esac
 }
+
+#  ____
+# |  _ \ _ __ ___ _ __
+# | |_) | '__/ _ \ '_ \
+# |  __/| | |  __/ |_) |
+# |_|   |_|  \___| .__/
+#                |_|
+
+
+isPiCheckReturnCode
+isPiCheckReturnCodeHardware
 
 if isTmpfs /tmp
 then
@@ -115,6 +170,49 @@ echo "See log file: $logFile for script output"
 exec 3>&1 4>&2
 trap 'exec 2>&4 1>&3' 0 1 2 3
 exec 1>${logFile} 2>&1
+
+
+# DisplayLink support
+for usbDevice in /sys/bus/usb/devices/*
+do
+  if [ -f ${usbDevice}/manufacturer ]
+  then
+    if [[ "$(cat ${usbDevice}/manufacturer)" == DisplayLink ]]
+    then
+      displayLinkPresent=1
+      break
+    fi
+  fi
+done
+
+if [ -n "${displayLinkPresent}" ]
+then
+
+  if [ -d /sys/module/evdi ]
+  then
+    displayLinkReady=ready
+  else
+    modprobe evdi
+    modprobeStatus=$?
+    if [ ${modprobeStatus} -eq 0 ]
+    then
+      displayLinkReady=ready
+    else
+      echo "DisplayLink devices are attached buy the evdi driver was unable to load. Skipping DisplayLink devices for this run."
+    fi
+  fi
+
+  if [ -n "${displayLinkPresent}" ] && [ -n "$displayLinkReady" ]
+  then
+    echo "At least one DisplayLink USB display has been detected. Running the required Xrandr commands to activate DisplayLink displays."
+    xrandr --listproviders | grep "modesetting" | grep -Po '(?<=^Provider )[0-9]+' | \
+    while read provider
+    do
+      echo "Activating DisplayLink Display #${provider}"
+      xrandr --setprovideroutputsource $provider 0
+    done
+  fi
+fi
 
 #  __  __       _
 # |  \/  | __ _(_)_ __
@@ -141,8 +239,8 @@ unclutter -idle 0.5 -root &
   connectedDisplays=($(xrandr|grep -E ' connected.*' | cut -d' ' -f1))
 
   # Start an x11vnc instance for debugging
-  isRaspberryPi && pkill -f -9 x11vnc
-  isRaspberryPi && x11vnc -bg -reopen -forever -display :0 >/dev/null 2>&1 &
+  isPiCheckReturnCode && pkill -f -9 x11vnc
+  isPiCheckReturnCode && x11vnc -bg -reopen -forever -display :0 >/dev/null 2>&1 &
 
   # Force 1080p
   for display in ${connectedDisplays[@]}
@@ -152,8 +250,8 @@ unclutter -idle 0.5 -root &
     then
       alignmentArgs="--right-of ${previousDisplay}"
     fi
-    isRaspberryPi && echo xrandr --output ${display} --mode ${x}x${y} ${alignmentArgs}
-    isRaspberryPi && xrandr --output ${display} --mode ${x}x${y} ${alignmentArgs}
+    isPiCheckReturnCode && echo xrandr --output ${display} --mode ${x}x${y} ${alignmentArgs}
+    isPiCheckReturnCode && xrandr --output ${display} --mode ${x}x${y} ${alignmentArgs}
 
 
     previousDisplay=${display}
@@ -195,6 +293,7 @@ do
   [ -z "$username" ] || [[ "$username" == null ]] && username="${globalUsername}"
   [ -z "$password" ] || [[ "$password" == null ]] && password="${globalPassword}"
   chromium --disk-cache-dir=${TMPDIR} --user-data-dir=/tmp/${configuredDisplay} --window-position=${xOffset},0 --kiosk --incognito "${URLs[0]}" >/dev/null 2>&1 &
+  connectedDisplaysChromiumPids+=($!)
   siteHandler ${URLs[0]}
 
   if [ ${#URLs[@]} -gt 1 ]
@@ -208,6 +307,5 @@ do
   echo "Display ${configuredDisplay} done."
 done
 
-closeFirstTab
-
+echo pids for each display are: "${connectedDisplaysChromiumPids}"
 cycleTabsIndefinitely
